// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Merriweather, JetBrains_Mono } from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";

// const jetbrainsMonoHeading = JetBrains_Mono({subsets:['latin'],variable:'--font-heading'});

// const merriweather = Merriweather({subsets:['latin'],variable:'--font-serif'});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-serif", merriweather.variable, jetbrainsMonoHeading.variable)}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Merriweather,
  JetBrains_Mono,
} from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";
import LoadingScreen from "../components/LoadingScreen";
import Navbar from "../components/layout/Navbar";



const jetbrainsMonoHeading = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-heading",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-serif",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {

  title: "Sumaya Islam | Full-Stack Developer",
  description:
    "Portfolio of Sumaya Islam — Full-Stack Developer specializing in React, Next.js, TypeScript, Node.js, and modern web applications.",
};

export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-serif",
        merriweather.variable,
        jetbrainsMonoHeading.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        <LoadingScreen />
        <Navbar />

        {children}
      </body>
    </html>
  );
}
